# Generated by Django 3.1.7 on 2022-02-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_payments', '0002_auto_20220131_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2bmpesapayment',
            name='week',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
