# Generated by Django 3.1.7 on 2022-02-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_payments', '0003_c2bmpesapayment_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverduePayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week_due', models.CharField(blank=True, max_length=200, null=True)),
                ('days_due', models.IntegerField(default=1)),
            ],
        ),
    ]
