# Generated by Django 3.1.7 on 2022-02-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_payments', '0004_overduepayments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overduepayments',
            name='installment_amount',
        ),
    ]
