# Generated by Django 3.1.7 on 2022-02-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_payments', '0005_remove_overduepayments_installment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='overduepayments',
            name='amount_due',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='b2cmpesapayment',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='c2bmpesapayment',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overduepayments',
            name='loan_amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
