# Generated by Django 3.1.7 on 2022-02-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_payments', '0007_paymentstoday'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstoday',
            name='loan_amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
