# Generated by Django 3.1.7 on 2022-02-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_payments', '0009_overduepayments_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2bmpesapayment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
