# Generated by Django 3.1.7 on 2022-02-22 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0055_loan_total_balance'),
        ('mpesa_payments', '0010_c2bmpesapayment_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2bmpesapayment',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='c2bmpesapayment',
            name='full_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loan'),
        ),
    ]
