# Generated by Django 3.1.7 on 2022-02-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_payments', '0011_auto_20220222_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c2bmpesapayment',
            name='name',
        ),
        migrations.AlterField(
            model_name='c2bmpesapayment',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
