# Generated by Django 3.1.7 on 2022-03-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_payments', '0013_auto_20220222_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c2bmpesapayment',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
