# Generated by Django 3.1.7 on 2021-12-22 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Type',
            fields=[
                ('loan_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type_name', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loan_type')),
            ],
        ),
    ]
