# Generated by Django 3.1.7 on 2021-12-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='id',
            new_name='user_id',
        ),
    ]
