# Generated by Django 3.1.7 on 2021-12-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20211222_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_type',
            name='loan_type_name',
            field=models.CharField(choices=[('SB', 'Small Business Loan'), ('M', 'Mortgage Loan'), ('P', 'Personal Loan')], default='P', max_length=2),
        ),
    ]
