# Generated by Django 3.1.7 on 2021-12-22 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0005_auto_20211222_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='user_id',
        ),
        migrations.AddField(
            model_name='loan',
            name='user_name',
            field=models.ForeignKey(db_column='username', default='', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
