# Generated by Django 3.1.7 on 2021-12-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_auto_20211222_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_type',
            name='loan_type_name',
            field=models.CharField(max_length=200),
        ),
    ]
