# Generated by Django 3.1.7 on 2021-12-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_auto_20211222_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan_Type',
            new_name='LoanType',
        ),
    ]
