# Generated by Django 3.1.7 on 2021-12-22 12:07

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_loan_num_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='num_days',
            field=computed_property.fields.ComputedTextField(blank=True, compute_from='calc_dueDate', default=0, editable=False, null=True),
        ),
    ]
