# Generated by Django 3.1.7 on 2021-12-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_auto_20211222_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_type_name',
            new_name='loan_type_id',
        ),
    ]
