# Generated by Django 3.1.7 on 2021-12-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_auto_20211222_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loantype'),
        ),
    ]
