# Generated by Django 3.1.7 on 2021-12-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_auto_20211222_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='num_days',
        ),
    ]
