# Generated by Django 3.1.7 on 2021-12-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_remove_loan_num_days'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan',
            table='LOAN',
        ),
    ]
