# Generated by Django 3.1.7 on 2021-12-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_auto_20211223_1524'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan',
            table=None,
        ),
    ]
