# Generated by Django 3.1.7 on 2021-12-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_auto_20211223_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type_name',
            field=models.CharField(choices=[('Personal Loan', 'Personal Loan'), ('Small Business Loan', 'Small Business Loan'), ('Mortgate', 'Mortgage')], default='Personal Loan', max_length=200),
        ),
    ]
