# Generated by Django 3.1.7 on 2021-12-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0022_auto_20211224_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='user_name',
            new_name='username',
        ),
    ]
