# Generated by Django 3.1.7 on 2021-12-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0023_auto_20211224_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
