# Generated by Django 3.1.7 on 2021-12-24 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0025_auto_20211225_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='username',
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
