# Generated by Django 3.1.7 on 2021-12-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0027_auto_20211225_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='username',
            new_name='user',
        ),
    ]
