# Generated by Django 3.1.7 on 2021-12-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0028_auto_20211226_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='user',
            new_name='username',
        ),
    ]
