# Generated by Django 3.1.7 on 2021-12-26 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0030_auto_20211226_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_type_name',
            new_name='loan_type',
        ),
    ]
