# Generated by Django 3.1.7 on 2021-12-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0031_auto_20211226_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantype',
            old_name='intereset_rate',
            new_name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='penalty_rate',
        ),
        migrations.AddField(
            model_name='loan',
            name='principal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
