# Generated by Django 3.1.7 on 2021-12-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0032_auto_20211226_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='principal',
        ),
    ]
