# Generated by Django 3.1.7 on 2021-12-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0038_auto_20211226_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_created',
            field=models.DateField(),
        ),
    ]
