# Generated by Django 3.1.7 on 2022-01-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0042_auto_20211226_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='min_collateral',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Hustle Yangu', 'Hustle Yangu'), ('Hustle Yangu Plus', 'Hustle Yangu Plus'), ('Jikuze Loan', 'Jikuze Loan')], default='Hustle Yangu', max_length=200),
        ),
    ]
