# Generated by Django 3.1.7 on 2022-01-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0044_auto_20220126_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
