# Generated by Django 3.1.7 on 2022-01-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0045_loantype_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantype',
            old_name='loan_type_id',
            new_name='id',
        ),
    ]
