# Generated by Django 3.1.7 on 2022-01-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0047_auto_20220127_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment_plan',
            field=models.CharField(blank=True, default='4 Weeks', max_length=200, null=True),
        ),
    ]
