# Generated by Django 3.1.7 on 2022-02-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0048_loan_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
