# Generated by Django 3.1.7 on 2022-02-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0049_loan_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
