# Generated by Django 3.1.7 on 2022-02-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0050_loan_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_due',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='initial_installment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
