# Generated by Django 3.1.7 on 2022-02-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0052_auto_20220211_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount_due',
            field=models.IntegerField(default=0),
        ),
    ]
