# Generated by Django 3.1.7 on 2022-02-06 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 0, 41, 39, 868910)),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 0, 41, 39, 868910)),
        ),
    ]
