# Generated by Django 3.1.7 on 2022-02-08 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_auto_20220207_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 9, 47, 34, 527116)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 9, 47, 34, 527116)),
        ),
    ]
