# Generated by Django 3.1.7 on 2022-02-11 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_auto_20220208_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 8, 44, 0, 719586)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 8, 44, 0, 719586)),
        ),
    ]
