# Generated by Django 3.1.7 on 2022-02-11 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0005_auto_20220211_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 8, 54, 45, 279638)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 8, 54, 45, 279638)),
        ),
    ]
