# Generated by Django 3.1.7 on 2022-02-19 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0011_auto_20220219_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 9, 35, 12, 229532)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 9, 35, 12, 229532)),
        ),
    ]
